"Importing Neccessary Libraries"
import streamlit as st
import joblib
import numpy as np
import pandas as pd
# <------------------------------------------------------------------>
# Loading the model
load_model = joblib.load("../Machine_learning_project/model/main_model.joblib")
# <------------------------------------------------------------------>
# Now creating streamlit UI
# <------------------------------------------------------------------>
st.set_page_config(
    page_title="Check Health",
    page_icon="https://img.freepik.com/premium-photo/red-heart-png-paper-craft-sticker-transparent-background_53876-1003443.jpg?semt=ais_hybrid&w=740&q=80" 
)
st.markdown(
    """
    <div style='text-align: center; padding: 10px 0'>
        <h1 style='color:#E63946;'>❤️ Heart-O</h1>
        <p style='font-size:18px;'>AI-powered Heart Health Risk Estimator</p>
    </div>
    """,
    unsafe_allow_html=True
)

# <------------------------------------------------------------------>

st.subheader("This app checks your heart health info and predict that you have Heart disease or Not")
st.info("🧠 **AI-Powered Insight** — This app analyzes your health metrics using a trained ML model.")
st.warning(
    "⚠️ **Disclaimer:** Predictions are not medical diagnoses. "
    "The model has ~89% accuracy and is for awareness only."
)
st.subheader("Now Fill This Form")
st.divider()
col_1, col_2 = st.columns(2)
with st.form("Heart checkup details"):
    with col_1:
        age=st.number_input("Enter Your Age",placeholder=40)
        sex=st.selectbox("Select your gender",["Male","Female","Transgender"], placeholder="Male")
        pain_type=st.selectbox("Selct Your Chest Pain Type",['ATA', 'NAP', 'ASY', 'TA'])
        resting_bp=st.select_slider("Enter your RestingBP (mm Hg)", options=range(0,201))
        cholestrol=st.select_slider("Enter your Cholestrol (mg/dL)", options=range(0,301))
        fastingbs=st.selectbox("Enter your FastingBS",[0,1])
        resting_egc=st.selectbox("Select Resting_EGC",['Normal', 'ST', 'LVH'])
        max_hr =st.select_slider("Enter your Max HR", options=range(0,201))
        st.divider()
    with col_2:
        exercise_angina = st.radio("select your Exercise Angina",["N","Y"])
        st_slope = st.radio("Select your ST_SLOPE", ["UP","Flat","Down"])
        old_peak = st.number_input("Select Your Old Peak",min_value=0, max_value=3)
        st.divider()
        
    button = st.form_submit_button("🔍 Analyze Heart Health")
    if button:
        st.success("Form Submitted successfully")

input_df = pd.DataFrame([{
    "Age": age,
    "Sex": sex,
    "ChestPainType": pain_type,
    "RestingBP": resting_bp,
    "Cholesterol": cholestrol,
    "FastingBS": fastingbs,
    "RestingECG": resting_egc,
    "MaxHR": max_hr,
    "ExerciseAngina": exercise_angina,
    "Oldpeak":old_peak,
    "ST_Slope": st_slope
}])
# <------------------------------------------------------------------>
# Sidebar
with st.sidebar:
    st.title("ℹ️ App Information")
    
    # Instructions Section
    st.markdown("### 📝 How to use")
    st.write("1. Fill in all the health parameters in the form.")
    st.write("2. Ensure your **Resting BP** and **Cholesterol** values are accurate for better results.")
    st.write("3. Click the **'Submit'** button to see the AI prediction.")
    
    st.divider()

    # Disclaimer Section
    st.markdown("### ⚠️ Medical Disclaimer")
    st.warning(
        "This tool is for **educational and awareness purposes only**. "
        "The predictions are generated by a machine learning model with an **89% accuracy rate**."
    )
    st.info(
        "**Important:** This is NOT a substitute for professional medical advice, diagnosis, or treatment. "
        "Always consult a qualified healthcare provider for any health concerns."
    )
    
    st.divider()
    st.caption("Developed for Health Awareness | Data-driven Insights")
# <------------------------------------------------------------------>
result = load_model.predict(input_df)
# <------------------------------------------------------------------>
if button:
    st.header("It's Our Model Prediction with 89% accuracy Don't take it ***seriously***")
    if result[0] == 1:
        st.error("🚨 **High Risk Detected** — Signs of potential heart disease.")
    else:
        st.success("✅ **Low Risk** — No significant indicators detected.")
    st.toast("Analysis complete 🚀", icon="❤️")
    confidence = 0.89
    st.progress(confidence)
    st.caption("Model Confidence Level")

# <------------------------------------------------------------------>